server:
  port: 8091

spring:
  application:
    name: user-service
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/Plazoleta
    platform: postgres
    password: Pragma1999.jeisson2060
  jpa:
    generate-ddl: 'true'
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8099/eureka